import { HorizontalBox, VerticalBox} from "std-widgets.slint";
import { SHeader } from "../modules/surrealism-ui/index.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    width: 100%;
    height: 100%;
    alignment: start;
    padding: 2px;
    spacing: 10px;
    HorizontalBox {
        SHeader {
            theme: Primary;
            value:  [{label:title,value:title}];
        }
        // Spacer
        Rectangle {}
    }
    @children
}