import { SText,SHeader } from "../../modules/surrealism-ui/index.slint";
import { Themes } from "../../modules/surrealism-ui/use/index.slint";
import { Page } from "../../components/index.slint";
import {ComboBox, GroupBox,HorizontalBox, LineEdit, Palette, VerticalBox} from "std-widgets.slint";
import { Button } from "../../modules/surrealism-ui/src/button/button.slint";
export component EvaluateComponent inherits Page {
    title: "季度考核";
    HorizontalLayout {
        Rectangle {
            width: 12%;
        }
        SText {
            width: 12%;
            text: "场所选择:";
            font-size: 15px;
        }

        ComboBox {
            width: 20%;
            model: [@tr("望亭"), @tr("太浦闸"), @tr("其他")];
        }

        Rectangle {
            width: 5%;
        }

        SText {
            width: 12%;
            text: "季度选择:";
            font-size: 15px;
        }

        ComboBox {
            width: 20%;
            model: [@tr("一季度"), @tr("二季度"), @tr("三季度"),@tr("三季度")];   
        }

        Rectangle { }
    }

    HorizontalLayout {
        Rectangle {
            height: 3%;
        }
    }

    Rectangle {
        border-width: 3px;
        border-color: Palette.foreground;
        padding: 8px;
        VerticalLayout {
            HorizontalBox {
                Rectangle { }

                SText {
                    width: 12%;
                    text: "合同名称:";
                    font-size: 18px;
                }

                LineEdit {
                    width: 50%;
                    placeholder-text: @tr("                   请填写合同名称!");
                    input-type: text;
                    font-size: 17px;
                }

                Rectangle { }
            }

            HorizontalBox {
                alignment: start;
                padding: 9px;
                SText {
                    width: 12%;
                    text: "1月数据:";
                    font-size: 15px;
                }

                LineEdit {
                    placeholder-text: @tr("0.0");
                    input-type: decimal;
                }

                Rectangle { }
            }

            HorizontalBox {
                alignment: start;
                padding: 9px;
                SText {
                    width: 12%;
                    text: "2月数据:";
                    font-size: 15px;
                }

                LineEdit {
                    placeholder-text: @tr("0.0");
                    input-type: decimal;
                }

                Rectangle { }
            }

            HorizontalBox {
                alignment: start;
                padding: 9px;
                SText {
                    width: 12%;
                    text: "3月数据:";
                    font-size: 15px;
                }

                SText {
                    theme: Primary;
                    width: 18%;
                    height: 20px;
                    text: "90.0";
                    font-size: 15px;
                }

                SText {
                    width: 40%;
                    height: 20px;
                    text: "(以下数据自动计算得到的平均数)";
                    font-size: 15px;
                }

                Rectangle { }
            }

            Rectangle {
                border-width: 1px;
                border-color: Palette.alternate-foreground;
                border-radius: 18px;
                VerticalLayout {
                    HorizontalBox {
                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }

                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }

                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }

                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }
                    }

                    HorizontalBox {
                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }

                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }

                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }

                        LineEdit {
                            placeholder-text: @tr("0.0");
                            input-type: decimal;
                        }
                    }
                }
            }

            HorizontalBox {
                SText {
                    width: 12%;
                    text: "综合评价:";
                }

                Rectangle {
                    height: 25px;
                    width: 80%;
                    border-width: 1px;
                    border-color: Palette.alternate-foreground;
                    HorizontalLayout {
                        alignment: start;
                        Rectangle {
                            width: 36%;
                        }

                        SText {
                            text: " 得分:  ";
                            font-size: 15px;
                        }

                        SText {
                            text: " 90 ";
                            font-size: 16px;
                            color: red;
                        }

                        Rectangle {
                            width: 6%;
                        }

                        SText {
                            text: " 等级:  ";
                            font-size: 15px;
                        }

                        SText {
                            text: " 优秀 ";
                            font-size: 15px;
                            color: green;
                        }

                        Rectangle { }
                    }
                }
            }
        }
    }
}
